name: "SSH OS"
description: "An opinionated terminal environment for working with Home Assistant"
version: "0.1.0"
slug: ssh_os
url: "https://github.com/joshmedeski/hass-ssh-os"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
options:
  authorized_keys: []
  password: ""
schema:
  authorized_keys:
    - str
  password: "str?"
ports:
  "22/tcp": null
  "60000-60010/udp": null
ports_description:
  "22/tcp": "SSH port"
  "60000-60010/udp": "Mosh UDP ports"
hassio_api: true
homeassistant_api: true
map:
  - homeassistant_config:rw
  - ssl:rw
  - share:rw
  - media:rw
  - backup:rw
